name: Build Documentation

on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

          
      - name: install sphinx
        run: pip install sphinx
      - name: install mkdocs
        run: pip install mkdocs mkdocs-material
      - name: Generate documentation
        run: |
          sphinx-build -b html .github/workflows/docs/source .github/workflows/docs/build
  
      - name: Deploy documentation
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .github/workflows/docs/build
          branch: gh-pages
          github_token: ${{ secrets.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 }}
          
       
